[package]
name = "jgtbrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
rusqlite = { version = "0", optional = true }

[features]
sqlite = ["dep:rusqlite"]
